a = int(input("input 1: "))
b = int(input("input 2: "))
c = int(input("input 3: "))
d = int(input("input 4: "))
e = int(input("input 5: "))
f = int(input("input 6: "))
g = int(input("input 7: "))
h = int(input("input 8: "))
i = int(input("input 9: "))
j = int(input("input 10: "))
print("a + b + c + d + e + f + g + h + i + j")